apiVersion: v1
kind: Service
metadata:
  name: cloudgenius-voting-service
  labels:
    app: cloudgenius-voting-app
spec:
  type: LoadBalancer  # Expose the app externally via an AWS ELB
  ports:
    - port: 80  # External port on which the app will be accessible
      targetPort: 3077  # The port your app listens on
  selector:
    app: cloudgenius-voting-app  # Match the Deployment's label
